"""Changed Order

Revision ID: 6804c402bdd5
Revises: 859428e4b4b4
Create Date: 2022-06-25 21:38:09.132307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6804c402bdd5'
down_revision = '859428e4b4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('quantities', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'quantities')
    # ### end Alembic commands ###
